# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvelicious' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvelicious

  pod 'StringMD5'
  pod 'SDWebImage'
  pod 'lottie-ios'

  target 'MarveliciousTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
